# ms-reservas · application.properties | Puerto: 8083 | BD: db_hotel_reservas

spring.profiles.active=dev

# spring.application.name: identifica este microservicio en el ecosistema distribuido
spring.application.name=ms-reservas
# server.port: puerto HTTP exclusivo del microservicio de reservas
server.port=8083
# spring.datasource.url: conexión a la base de datos independiente de reservas
spring.datasource.url=jdbc:mysql://localhost:3306/db_hotel_reservas?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
# spring.datasource.username: usuario MySQL con permisos sobre db_hotel_reservas
spring.datasource.username=root
# spring.datasource.password: contraseña del usuario MySQL
spring.datasource.password=
# spring.datasource.driver-class-name: clase del driver JDBC de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.hibernate.ddl-auto: crea o actualiza las tablas al arrancar el microservicio
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql: habilita la impresión de consultas SQL en la consola
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql: formatea el SQL impreso en consola
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect: dialecto MySQL para que Hibernate genere SQL correcto
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


// Configuración de SpringDoc para generar documentación OpenAPI y habilitar Swagger UI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# ── EUREKA CLIENT ─────────────────────────────────────────────
# Registra este microservicio en el servidor Eureka del hotel (puerto 8761)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/